### ISSUE TITLE
RADIUS settings doesn't updated in Directory Service.

### ISSUE THREAD

**Issue by dudutwizer** [aws-quickstart/quickstart-duo-mfa#1]
State Manager : Success
RADIUS Instance : Launch successfully
#Instances is 1 (Only one RADIUS Server)

When I navigate to Directory Service console the Multi-factor authentication tab is still blank. (Not even trying to set up RADIUS server)

Error log from the Lambda:
"Found addresses: [], but two are required."

edit after debug:

Lambda line #134: 
#{"Name": "tag:RadiusConfigured", "Values": ["True"]},
this returns zero for some-reason

Thanks

**Comment by barnesrobert** [comment]
Hi, dudutwizer.

I'd recommend walking through the "Troubleshooting MFA implementation" section in the deployment guide, found [here](https://aws-quickstart.s3.amazonaws.com/quickstart-duo-mfa/doc/duo-mfa-for-aws-directory-service-on-the-aws-cloud.pdf).

There could have been an issue configuring the RADIUS servers with the Duo auth proxy service. Take a look and let us know if you're not able to resolve this.

Regards,
Rob

**Comment by sshvans** [comment]
Closing it due to inactivity. Please re-open it, if you are still facing the issue.

**Comment by kriscloud** [comment]
I am having same issue, after deployment, doesn't add radius config into Directory (AD Connector).  Troubleshooting doesn't help.

**Comment by toytown** [comment]
I am also having same issue, after deployment. This is the second time and it is frustrating. Troubleshooting does not help.  The MFA part is not updated in the Directory and always get "Found addresses: [], but two are required."
