### ISSUE TITLE
Please update the walkthrough document

### ISSUE THREAD

**Issue by rm756215** [aws-quickstart/quickstart-duo-mfa#11]
Hello Team,

The document which walks us through this configuration process is old. I see there have been quite a few changes made related to Directory Services console, Systems Manager console with respect to the terms mentioned in this document. For Example, Step 3, point 5 states "Choose the Instances tab." but the new console has the "Resources" tab instead. There are many such terms which are different now in newer versions of console.

[+] Walkthrough document: https://aws-quickstart.s3.amazonaws.com/quickstart-duo-mfa/doc/duo-mfa-for-aws-directory-service-on-the-aws-cloud.pdf

**Comment by barnesrobert** [comment]
Thank you for your input! We will evaluate the guide for such changes.

**Comment by davmayd** [comment]
We've completely refactored the Quick Start, it now leverages ECS with Fargate rather than EC2. This issue no longer applies. The deployment guide has also been rewritten.
