### ISSUE TITLE
Invalid characters allowed for RADIUS Secret

### ISSUE THREAD

**Issue by EmpathicKernel** [aws-quickstart/quickstart-duo-mfa#12]
There is a character that can be contained in the RADIUS Secret that Directory Service or Lambda does not like (DS RADIUS change simply fails).

I was unable to determine which character it was as I was frantically trying to fix MFA on the Directory although the Secrets cycle caused my Directory Services MFA configuration to fail. Once I cycled the RADIUS secret again, it began working again. I had forced new proxies to spawn but all had the issue.

**Comment by EmpathicKernel** [comment]
Just had this happen again. Attached was the secret causing the issue. Forcing a rotation fixed the issue. 

![image](https://user-images.githubusercontent.com/31391660/79261673-2de17f80-7e5e-11ea-80b5-9bf7bc259bc2.png)

**Comment by mhowison** [comment]
We have experienced the same issue in two Duo QuickStart deployments, one in an account with an AD Connector to Azure AD and the other in an account with an AWS Managed Microsoft AD.
In both accounts, RADIUS suddenly failed.
To fix, we had to manually disabled RADIUS in Directory Service and then force the RADIUS secret to cycle in Secrets Manager.

**Comment by gatesman466** [comment]
I'm working through this Quickstart for the first time and discovered the below section in the CFN. Changing the characters in the "Exclude Characters" line may solve this problem. The original line contains '"=,' but if you include all the specials EmpathicKernel identified above, it might solve this problem. 

  **DuoConfigurationSettingsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub DuoConfigurationSettings-${DirectoryServiceId}
      Description: Duo Configuration Settings
      GenerateSecretString:
        SecretStringTemplate: !Sub |
          {
            "DuoSecretKey":"${DuoSecretKey}",
            "DuoIntegrationKey":"${DuoIntegrationKey}",
            "DuoApiHostName":"${DuoApiHostName}"
          }
        GenerateStringKey: RadiusSharedSecret
        PasswordLength: 25
        # Do not include the following characters.
        ExcludeCharacters: '"=,-|$;~.('
      Tags:
      - Key: duo:DirectoryServiceId
        Value: !Ref DirectoryServiceId**

**Comment by EmpathicKernel** [comment]
I had narrowed it down to ";" and "|" as the other special characters were being used in other connections of ours without issue. Also ironically one of our other connections failed yesterday and this was it's secret before I rotated:

<img width="188" alt="Screen Shot 2020-05-05 at 10 52 29 AM" src="https://user-images.githubusercontent.com/31391660/81080231-85ec2e80-8ebe-11ea-95a3-c9b409b9d042.png">

**Comment by gatesman466** [comment]
EmpathicKernel, while it's not a complete test, I adjusted my Quickstart to exclude this set of characters, base on your feedback.
**ExcludeCharacters: '"=,;|-<>*()[]?'**

Then I rotated the RADIUS secret 5 times. After each rotation I checked the RotateRadiusSharedSecret log for success or failure, and also logged in with an OpenVpn client to test DUO functionality (I'm using this setup for MFA on AWS Client VPN). It worked every time.

**Comment by sshvans** [comment]
@gatesman466 Thanks for the thorough testing and narrowing it down to specific characters. Can you describe which resource/service didn't like these characters?
Also, if you want to create a PR with your described changes, I am happy to accept and merge it. Otherwise, I'll get to it soon to incorporate the fixes.

**Comment by davmayd** [comment]
We've completely refactored the Quick Start, it now leverages ECS with Fargate rather than EC2. This issue no longer applies.
