### ISSUE TITLE
Issue when EC2 instance pulls package

### ISSUE THREAD

**Issue by brokenmasonjars** [aws-quickstart/quickstart-duo-mfa#15]
When I kick the template off and the SSM document runs to pull the latest Duo security config, it errors out.  I tried running the runbook separately and the same error occurs (See below).  When i go into session manager and run it manually step by step it works fine.

![Error](https://user-images.githubusercontent.com/68665343/88226209-b8920180-cc39-11ea-912a-f8ba7098870c.jpg)

**Comment by davmayd** [comment]
We've completely refactored the Quick Start, it now leverages ECS with Fargate rather than EC2. This issue no longer applies.
