### ISSUE TITLE
Rotating secrets causes lockouts

### ISSUE THREAD

**Issue by jf76** [aws-quickstart/quickstart-duo-mfa#16]
If the managed AD service is in maintenance mode while secrets are updating, it can lead to the service locking out everyone until the secrets are rotated successfully again.  See Also:  Case ID 7216850251.

The secret is stored in AWS Secrets Manager and rotated every 7 days.

Rotation is implemented by a Lambda function which generates the new secret and then it calls the SSM Run Document.

This Document updates the DUO AuthProxy configuration by updating the radius_secret_1 and radius_secret_2 settings with the new secret. After the instances are updated, an SNS message is sent to the SNS topic.

Messages sent to the SNS topic trigger the Lambda function UpdateDirectoryServiceMfaSettings-ds-instanceID which updates the Shared secret code setting in the Directory Service’s MFA settings.

If the directory is in maintenance mode, the lambda errors and does not complete.  This causes the radius servers to hold the new key while the directory server holds the old key. This causes everyone to be locked out.  This condition has happened to us twice now when the directory service was either being patched or snapshotting.

As a work around, we had to manually rotate the keys.  Feature/bug request,  check that the directory service is not under maintenance before updating the proxy hosts with new secrets?  or on error backout changes?  something like that.

**Comment by barnesrobert** [comment]
Hi, jf76.

Thank you for your input and recommendation. We will add this to our backlog.

- Rob

**Comment by davmayd** [comment]
We've completely refactored the Quick Start, it now leverages ECS with Fargate rather than EC2. This issue no longer applies.
