### ISSUE TITLE
QuickStart fails to deploy because EC2 bootstrap command silently errors

### ISSUE THREAD

**Issue by mhowison** [aws-quickstart/quickstart-duo-mfa#18]
We have used this QuickStart successfully several times in the past, as recently as April 2020.
However, as of Jan 2021 it now fails to correctly deploy because the EC2 instances do not complete the bootstrapping phase in SSM.
The "Duo-RadiusProxyBootstrapDocument" SSM command fails in the third step (ConfigureCloudWatchLogsAgent) with an example error message below. I sshed into the instance and found that the missing configuration file it is looking for and can't find is actually at the path /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/ssm__DuoRadiusConfiguration_d-XXXXXXXXXX_CloudWatchAgentConfiguration (e.g. without the .tmp extension).
Surprisingly, the error does not cause the SSM command to fail, so the QuickStart appears to deploy correctly, but the EC2 instances are not configured with the Duo RADIUS proxy software and do not write any logs to the CloudWatch Logs group.
As a result, the RADIUS integration with the directory also fails.

The stage that is failing uses the "AmazonCloudWatch-ManageAgent" document, so perhaps there has been a change to that document between April 2020 (when we last successfully ran the QuickStart) and now?

----

/opt/aws/amazon-cloudwatch-agent/bin/config-downloader --output-dir /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d --download-source ssm:/DuoRadiusConfiguration/d-XXXXXXXXXX/CloudWatchAgentConfiguration --mode ec2 --config /opt/aws/amazon-cloudwatch-agent/etc/common-config.toml --multi-config default

Region: us-east-1

credsConfig: map[]

Successfully fetched the config and saved in /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/ssm__DuoRadiusConfiguration_d-XXXXXXXXX_CloudWatchAgentConfiguration.tmp

Start configuration validation...

/opt/aws/amazon-cloudwatch-agent/bin/config-translator --input /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json --input-dir /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d --output /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.toml --mode ec2 --config /opt/aws/amazon-cloudwatch-agent/etc/common-config.toml --multi-config default

Valid Json input schema.

I! Detecting runasuser...

No csm configuration found.

No metric configuration found.

Configuration validation first phase succeeded

/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent -schematest -config /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.toml

Configuration validation second phase succeeded

Configuration validation succeeded

amazon-cloudwatch-agent start/running, process 2833

----------ERROR-------

2021/01/07 15:56:35 Reading json config file path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/ssm__DuoRadiusConfiguration_d-XXXXXXXXXX_CloudWatchAgentConfiguration.tmp ...

**Comment by davmayd** [comment]
We've completely refactored the Quick Start, it now leverages ECS with Fargate rather than EC2. This issue no longer applies.
