### ISSUE TITLE
Console Sign-In Authentication Failed After MFA enabled

### ISSUE THREAD

**Issue by jonrau1** [aws-quickstart/quickstart-duo-mfa#2]
Confirmed that the Stack deployed correctly; State Manager Associations are all successful, MFA is shown as Complete in Managed AD and the RADIUS Server IP addresses match the deployed Instances.
Security Group rules all have 1812 inbound & outbound to all SG's and the VPC, and multiple users and IAM delegated roles have been created. These previously worked just entering in the user name & password, now with MFA enabled I get an error like this:
"Your user name or password can't be processed. You may also need to specify a domain name in the username (such as domain\username). If you don't know your domain name, contact your administrator."
I have disabled and re-enabled Application Access URL as well as AWS Management Console login. I have also removed and re-added different AD Users and have tried logging in with both the Short Name & full Domain DNS Name without luck.
Is there a misconfiguration on the DUO side?

**Comment by jonrau1** [comment]
Users were not properly enrolled in DUO, re-enrollment fixed the issue

**Comment by barnesrobert** [comment]
Great, thanks for the update!
