### ISSUE TITLE
Errors starting RADIUS EC2 - Duo-MFA-for-AWS-Directory-Service-InstanceProfile - Client error on launch

### ISSUE THREAD

**Issue by skrausedxccom** [aws-quickstart/quickstart-duo-mfa#27]
hi, 
I've got an issue: the autoscaling group does not launch the EC2s Duo Proxies, they are immediately terminated after launch. 

STATEREASON	Client.InternalError	Client.InternalError: [instance.log](https://github.com/aws-quickstart/quickstart-duo-mfa/files/6416083/instance.log)

maybe its because EC2 IAM role "Duo-MFA-for-AWS-Directory-Service-InstanceProfile-xxxxxx" is refrenced but does not exist?  I do not find it in IAM.

Thanks for your help.

**Comment by davmayd** [comment]
We've completely refactored the Quick Start, it now leverages ECS with Fargate rather than EC2
