### ISSUE TITLE
SSO MFA

### ISSUE THREAD

**Issue by vennemp** [aws-quickstart/quickstart-duo-mfa#3]
Will this work if we are using ADFS to federate authentication to multiple applications (AWS, third-party VPN provider, etc)?  

The following statement in the release isn't clear to me  It says you configure your own MFA and then goes on to suggest that Duo MFA configured with this method will work..
```
If you use a federation mechanism like AWS Single Sign-On (AWS SSO) or Active Directory Federation Services (AD FS) with a Directory Service option, you configure your own MFA. Using Duo MFA, you log in to the AWS Management Console, and then use Duo authentication methods including Duo Push through Duo Mobile, and your Active Directory credentials to authenticate to AWS.
```

**Comment by davmayd** [comment]
We've completely refactored the Quick Start, it now leverages ECS with Fargate rather than EC2. This issue no longer applies.
