### ISSUE TITLE
Solution doesn't enable MFA on directory

### ISSUE THREAD

**Issue by DhimantR** [aws-quickstart/quickstart-duo-mfa#39]
Hi,

This solution doesn't enable MFA on directory.

- I have implemented on Ec2 
- Reviewing lambda function UpdateDirectoryServiceMfaSettings-d-id, reviewing its logs found that it is not moving forward because of this error
- Found addresses: ["10.1.1.89"], but two are required.

Would you be able to fix this issue on the deployment.

**Comment by davmayd** [comment]
Resolved by https://github.com/aws-quickstart/quickstart-duo-mfa/pull/44
