### ISSUE TITLE
Solution does not enable RADIUS MFA in AWS AD - Directory Service

### ISSUE THREAD

**Issue by brlink-tadeucamillo** [aws-quickstart/quickstart-duo-mfa#40]
Hi,

Not enabling when trying to configure MFA DUO Software following procedure https://aws-quickstart.s3.amazonaws.com/quickstart-duo-mfa/doc/duo-mfa-for-aws-directory-service-on-the -aws-cloud.pdf

- Run CloudFormantion as per documentation https://fwd.aws/nXE9E successfully.

- However, when checking the RADIUS status in Directory Service, it does not activate.

- Analyzing the logs via CloudWatch lambda function UpdateDirectoryServiceMfaSettings-d-id generates the following message Found addresses: [], but two are required.

Would you be able to fix this issue on the deployment.

**Comment by davmayd** [comment]
Resolved by https://github.com/aws-quickstart/quickstart-duo-mfa/pull/44

**Comment by davmayd** [comment]
Resolved by https://github.com/aws-quickstart/quickstart-duo-mfa/pull/44
