### ISSUE TITLE
EC2 Instances never check into SSM

### ISSUE THREAD

**Issue by rtestani** [aws-quickstart/quickstart-duo-mfa#5]
When quickstart template is run, the EC2 instances never check into SSM to be configured.

I found this is due to the EC2 instances not being able resolve DNS.  

Outbound DNS is not configured in the DuoRadiusProxySecurityGroup and thus not allowed out of the EC2 instances.

I suggest either allowing DNS outbound to all hosts.  Or better yet, allowing outbound to only th discovered directory services group/IPs.

**Comment by barnesrobert** [comment]
Hi, Rich. 

Outbound connectivity by the RADIUS hosts is provided by whatever your domain controllers use, which is generally through NAT gateways. Also, please confirm that there is a route to the internet (0.0.0.0/0) in route table associated with the RADIUS servers.

**Comment by rtestani** [comment]
All routing is correct.  I've dumped EC2 instances into the same VPC adn subnet and they can get out to the internet and resolve DNS using the domain controllers.

The issue lies in the security group that gets assigned to the EC2 RADIUS Hosts

I edited the cloud formation to assign a key pair to the RADIUS servers as a test.  I ssh'd in and found that they could not resolve DNS.  As soon as I added DNS to be allowed outbound on the security group that gets attached to the RADIUS hosts, they checked into SSM and everything worked.

I tested and found that if I edited this section under DuoRadiusProxySecurityGroup:
```
"SecurityGroupEgress": [
                    {
                        "IpProtocol": 6,
                        "FromPort": 80,
                        "ToPort": 80,
                        "CidrIp": "0.0.0.0/0"
                    },
                    {
                        "IpProtocol": 6,
                        "FromPort": 443,
                        "ToPort": 443,
                        "CidrIp": "0.0.0.0/0"
                    }
                ],
```
to this:
```
"SecurityGroupEgress": [
                    {
                        "IpProtocol": 6,
                        "FromPort": 80,
                        "ToPort": 80,
                        "CidrIp": "0.0.0.0/0"
                    },
                    {
                        "IpProtocol": 6,
                        "FromPort": 443,
                        "ToPort": 443,
                        "CidrIp": "0.0.0.0/0"
                    },
                    {
                        "IpProtocol": 17,
                        "FromPort": 53,
                        "ToPort": 53,
                        "CidrIp": "0.0.0.0/0"
                    }
                ],
```

the Cloudformation deployed and the RADIUS hosts were able to check into SSM

**Comment by barnesrobert** [comment]
Thanks for the additional context. Curious--are you using a custom DHCP options set for that VPC?

**Comment by rtestani** [comment]
Yes, we are.  You have to when using AWS' directory service.  DHCP provided DNS is pointing to the two DCs.

**Comment by davmayd** [comment]
We've completely refactored the Quick Start, it now leverages ECS with Fargate rather than EC2. This issue no longer applies.
