### ISSUE TITLE
Connection from Duo to Fargate Task

### ISSUE THREAD

**Issue by thales-caylent** [aws-quickstart/quickstart-duo-mfa#74]
When following the post-deployment steps to set up User syncing in Duo, I don't see a way that this could work.

The [documentation](https://aws-quickstart.github.io/quickstart-duo-mfa/#_postdeployment_steps) states that we should use the Fargate's tasks IP addresses in Duo's setup, but there's no way Duo can ever reach the task because it is deployed in private subnets with a NAT Gateway, thus inbound traffic is not allowed. No NLB/ALB are created with this stack, so the Fargate Task is completely unreachable from the internet.

How should this be addressed so Duo can sync users with AWS Managed AD?

**Comment by AaronAtDuo** [comment]
@thales-caylent The way Duo does user sync via the Authentication Proxy does not involve an inbound connection from the internet.  Instead, the Authentication Proxy reaches out to Duo cloud and establishes a long-lived TLS connection.  At that point, the Duo cloud service can send queries to the Authentication Proxy, which it forwards on to the directory.  The Authentication Proxy then sends the response data back up to the Duo cloud service.

So, it is necessary that the Authentication Proxy be able to reach the directory, but nothing else needs to.

**Comment by thales-caylent** [comment]
Perfect! Thanks for the detailed explanation, @AaronAtDuo!
